version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: SonarCloud

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - cmp-{{ checksum "pom.xml" }}
            - cmp
      - run:
          name: Install Leiningen
          command: |
            mkdir ~/bin &&
            curl --silent --show-error --location --fail --retry 3 --output ~/bin/lein https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein &&
            chmod +x ~/bin/lein
      - run:
          name: Maven build
          command: mvn dependency:go-offline -B
      - run:
          name: Quality quantification
          command: bin/test.sh -B -Psonarcloud sonar:sonar
      - save_cache:
          paths:
            - ~/.m2
          key: cmp-{{ checksum "pom.xml" }}
      - store_test_results:
          path: target/surefire-reports
